"""empty message

Revision ID: 700c033c0e74
Revises: dbcdec35c2cb
Create Date: 2021-11-04 19:51:28.749015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700c033c0e74'
down_revision = 'dbcdec35c2cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
